football/team/kotoko/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('home/', views.welcome_section, name='home'),
    path('players/', views.list_players, name='players'),
    path('home/', views.welcome_section, name='master'),
    path('about/<int:id>', views.about_player, name='about'),
    path('add/', views.add_player, name='add')
]

football/team/staff/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.hearts_home, name='home'),
    path('add/', views.add_staff, name='add-staff' ),
    path('list/', views.list_staff, name='staff-list')
]

football/team/team/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kotoko.urls')),
    path('staff/', include('staff.urls'))
]

football/team/kotoko/models.py
from django.db import models

# Create your models here.
class Player(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    member_since = models.DateField(auto_now_add=True, blank=False, null=False)
    
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    

football/team/staff/models.py
from django.db import models

# Create your models here.
class Staff(models.Model):
    name = models.CharField(max_length=200)
    age = models.IntegerField()
    email = models.EmailField(max_length=50)
    role = models.CharField(max_length=100)
    nationality = models.CharField(default='Ghanaian', max_length=100)
    
    def __str__(self):
        return f'{self.name}'

football/team/kotoko/forms.py
from django import forms

class AddPlayerInput(forms.Form):
    first_name = forms.CharField(max_length=100, label='First Name')
    last_name = forms.CharField(max_length=100)
    address = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=100)
    member_since = forms.DateField()

football/team/staff/forms.py
from django import forms
from .models import Staff


class StaffForm(forms.ModelForm):
    class Meta:
        model = Staff
        fields = [
            'name',
            'age',
            'email',
            'role'
        ]

football/team/kotoko/views.py
from django.shortcuts import render
from .models import Player
from .forms import AddPlayerInput
from django.http import HttpResponse

# Create your views here.
def welcome_section(request):
    return render(request, 'index.html')


def list_players(request):
    player = Player.objects.values()
    context = {
        'object': player
    }
    return render(request, 'players.html', context)


def about_player(request, id):
    player = Player.objects.get(id=id)
    context = {
        'object': player
    }
    return render(request, 'about.html', context)


def add_player(request):
    if (request.method == 'POST'):
        player = AddPlayerInput(request.POST or None)
        if (player.is_valid()):
            first_name = player.cleaned_data['first_name'] # receives data from the form as dict
            last_name = player.cleaned_data['last_name']
            address = player.cleaned_data['address']
            email = player.cleaned_data['email']
            member_since = player.cleaned_data['member_since']
            
            newPlayer = Player.objects.create(
                first_name=first_name,
                last_name=last_name,
                address=address,
                email=email,
                member_since=member_since
            )
            newPlayer.save()
        
    player = AddPlayerInput()
    context = {
        'form': player
    }
    return render(request, 'add_player.html', context)

football/team/staff/views.py
from django.shortcuts import render
from .forms import StaffForm
from .models import Staff



# Create your views here.
def hearts_home(request):
    return render(request, 'base.html')


def add_staff(request):
    form = StaffForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = StaffForm()
    
    context = {
        'form': form
    }
    return render(request, 'add-staff.html', context)


def list_staff(request):
    staff = Staff.objects.values()
    context = {
        'staff': staff
    }
    return render(request, 'staff.html', context)

football/team/kotoko/templates/about.html
{% extends "master.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Details | {{ object.first_name }} {{ object.last_name }} {% endblock %}</title>
</head>
<body>
    {% block content %}
    <div class="container">
        <h1 id="name">{{ object.first_name }} {{ object.last_name }}</h1>
        <p>Address: {{ object.address }}</p>
        <p>Email: {{ object.email }}</p>
        <p>Member Since: {{ object.member_since }}</p>
    </div>
    {% endblock %}
</body>
</html>

football/team/kotoko/templates/add_player.html
{% extends "master.html" %}

{% block title %}
Add New Player
{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" id="add-player">Add Player</button>
</form>
{% endblock %}

football/team/kotoko/templates/index.html
{% extends 'master.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Welcome | Kotoko {% endblock %}</title>
</head>
<body>
    {% block content %}
    <main class="main">
        <h1>Welcome to our site</h1>
        <p>Click <a href="/players">here</a> to see the names of all our players</p>
    </main>
    {% endblock content %}
</body>
</html>

football/team/kotoko/templates/master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <nav class="nav-bar">
        <a href="/home">Home</a>
        <a href="/players">Players</a>
    </nav>

    {% block content %}

    {% endblock %}

    <footer class="buttom-section">
        <div class="icons">
            <p id="get-in-touch">Get in touch</p>
            <div class="socials">
                <a href="#"><img src="{% static 'facebook.svg' %}" alt="facebook Icon" class="icon"></a>
                <a href="#"><img src="{% static 'instagram.svg' %}" alt="Instagram Icon" class="icon"></a>
                <a href="#"><img src="{% static 'x.svg' %}" alt="x icon" class="icon"></a>
                <a href="#"><img src="{% static 'whatsapp.svg' %}" alt="whatsapp icon" class="icon"></a>
            </div>
        </div>
    </footer>
</body>
</html>

football/team/kotoko/templates/players.html
{% extends "master.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} List of all memebers {% endblock %}</title>
</head>
<body>
    {% block content %}
    <main class="container">

        <h1 class="player">All Players</h1> 
        <ul>
            {% for player in object %}
            <li><a href="/about/{{player.id}}">{{ player.first_name }} {{ player.last_name }}</a></li>
            {% endfor %}
        </ul>

    </main>
    {% endblock content %}
</body>
</html>

football/team/staff/templates/add-staff.html
{% extends "master-staff.html" %}

{% block title %}Add Staff{% endblock %}


{% block content %}
<form action="" method="post" class="col-4 mx-auto border border-tertiary p-4 mt-4 rounded shadow-lg">
    {% csrf_token %}
    <div class="mb-3">
        <label for="id_name" class="form-label">Name:</label>
        <input type="text" class="form-control form-control-lg" id="id_name" aria-describedby="emailHelp" name="name" maxlength="200" required>
    </div>
    <div class="mb-3">
        <label for="id_age" class="form-label">Age:</label>
        <input type="number" class="form-control form-control-lg" id="id_age" aria-describedby="emailHelp" name="age" required>
    </div>
    <div class="mb-3">
        <label for="id_email" class="form-label">Email:</label>
        <input type="email" class="form-control form-control-lg" id="id_email" aria-describedby="emailHelp" name="email" required maxlength="50">
    </div>
    <div class="mb-3">
        <label for="id_role" class="form-label">Role:</label>
        <input type="text" class="form-control form-control-lg" id="id_role" aria-describedby="emailHelp" name="role" required maxlength="100">
    </div>
    <!-- {{ form.as_p }} -->
    <div class="d-grid my-4">
        <button class="btn btn-primary btn-lg" id="add-plahyer" type="submit">Save</button>
    </div>
</form>
{% endblock %}

football/team/staff/templates/base.html
{% extends "master-staff.html" %}

{% block title %}
Home | Staff
{% endblock %}

{% block content %}
<p id="lorem">{% lorem 8 %}</p>
{% endblock %}

football/team/staff/templates/master-staff.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head> 
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.png' %}" type="image/x-icon">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <nav class="nav-bar">
        <a href="{% url 'home' %}">Home</a>
        <a href="{% url 'add-staff' %}">Add Staff</a>
        <a href="{% url 'staff-list' %}">Staff</a>
    </nav>

    {% block content %}

    {% endblock %}

    <footer class="buttom-section">
        <div class="icons">
            <p id="get-in-touch">Get in touch</p>
            <div class="socials">
                <a href="#"><img src="{% static 'facebook.svg' %}" alt="facebook Icon" class="icon"></a>
                <a href="#"><img src="{% static 'instagram.svg' %}" alt="Instagram Icon" class="icon"></a>
                <a href="#"><img src="{% static 'x.svg' %}" alt="x icon" class="icon"></a>
                <a href="#"><img src="{% static 'whatsapp.svg' %}" alt="whatsapp icon" class="icon"></a>
            </div>
        </div>
    </footer>
</body>
</html>

football/team/staff/templates/staff.html
{% extends "master-staff.html" %}

{% block title %}
List | Staff
{% endblock %}

{% block content %}
<main class="container">
    <h1 class="player">Staff Members</h1>
    <ul>
        {% for member in staff %}
        <li>{{ member.name }}</li>
        {% endfor %}
    </ul>
</main>
{% endblock %}